In [1]:
import nakdan_preprocessed_data.model as m
import data_prep.load_vocab as v
import nakdan_preprocessed_data.process_nakdan_data as d
from sklearn.model_selection import train_test_split
import torch

embeddings, vocab, word_list = v.load_vocab()
network = m.Transformer(2,embeddings)
x,y = d.get_phrase_dataset(256,"test_dataset")
#y[y==1] = 0
#y[y==2] = 1
y[y==2] = 1
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
network.to(torch.device("cuda"))
print(torch.device("cuda"))


cuda


In [3]:
#network.fit(8, 50,X_train,y_train,X_test,y_test,torch.tensor([1,2]))
#>>TRANSFORER network.fit(8, 100,X_train,y_train,X_test,y_test,torch.tensor([1,4]))
network.fit(100, 100,X_train,y_train,X_test,y_test)

training
epochs: 16
Batch: 100
********************************
epoch: 0 :loss: 0.21556351235195925 :acc: 0.9073083660082059
confusion:
[[0.83010269 0.0677743 ]
 [0.0249188  0.07720421]]
validation loss: 0.20240468057719144 :validation acc: 0.916770930815508
validation confusion
[[0.82629189 0.05532259]
 [0.02793097 0.09045455]]
time: 59595
********************************
epoch: 1 :loss: 0.2125035023580403 :acc: 0.9086410277488252
confusion:
[[0.83009697 0.0664468 ]
 [0.02492452 0.07853172]]
validation loss: 0.19770005670460788 :validation acc: 0.9166584224598929
validation confusion
[[0.83307854 0.06216995]
 [0.02114433 0.08360718]]
time: 60634
********************************
epoch: 2 :loss: 0.20916390561894194 :acc: 0.9100040300732916
confusion:
[[0.83015538 0.06512518]
 [0.02486611 0.07985333]]
validation loss: 0.19292533262209458 :validation acc: 0.9198796373663101
validation confusion
[[0.83105397 0.05694567]
 [0.02316889 0.08883147]]
time: 60837
********************************

In [3]:
for g in network.optimizer.param_groups:
    g['lr'] = 0.001

In [2]:
network.load("TRANSFORMER.9269")

loaded state from  TRANSFORMER.9269


In [ ]:
#network.fit(8, 50,X_train,y_train,X_test,y_test,torch.tensor([1,2]))
#>>TRANSFORER network.fit(8, 100,X_train,y_train,X_test,y_test,torch.tensor([1,4]))
network.fit(100, 100,X_train,y_train,X_test,y_test)

training
epochs: 100
Batch: 100


C:\Users\ygold\scribe_2021_11\Scribe\nakdan_preprocessed_data\model.py:764: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  i, o = torch.tensor(X[indices]), torch.tensor(Y[indices])
C:\Users\ygold\.conda\envs\scribe\lib\site-packages\sklearn\utils\validation.py:67: FutureWarning: Pass labels=[0, 1] as keyword args. From version 0.25 passing these as positional arguments will result in an error
  warnings.warn("Pass {} as keyword args. From version 0.25 "
C:\Users\ygold\scribe_2021_11\Scribe\nakdan_preprocessed_data\model.py:711: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  i, o = torch.tensor(X[indices]), torch.tensor(Y[indices])


********************************
epoch: 0 :loss: 0.18711470292039115 :acc: 0.9192625327782735
confusion:
[[0.82895416 0.05467232]
 [0.02606733 0.0903062 ]]
validation loss: 0.17176760326732288 :validation acc: 0.928359082553476
validation confusion
[[0.83071393 0.04811588]
 [0.02350894 0.09766125]]
time: 48247
********************************
epoch: 1 :loss: 0.18449972080041285 :acc: 0.9203094419007677
confusion:
[[0.82905972 0.05371938]
 [0.02596176 0.09125914]]
validation loss: 0.1697600543498993 :validation acc: 0.9286858288770053
validation confusion
[[0.82435805 0.0414764 ]
 [0.02986481 0.10430073]]
time: 61705
********************************
epoch: 2 :loss: 0.18384953523607558 :acc: 0.920623971155119
confusion:
[[0.8290315  0.05338429]
 [0.02598999 0.09159423]]
validation loss: 0.1703520428050648 :validation acc: 0.9286970254010698
validation confusion
[[0.83004169 0.04711146]
 [0.02418117 0.09866567]]
time: 48160
********************************
epoch: 3 :loss: 0.18278576590154

********************************
epoch: 27 :loss: 0.1656711396833533 :acc: 0.9292741059906684
confusion:
[[0.82971401 0.04541371]
 [0.02530748 0.09956481]]
validation loss: 0.1563292292031375 :validation acc: 0.9339339070855612
validation confusion
[[0.83193338 0.043781  ]
 [0.02228949 0.10199613]]
time: 48286
********************************
epoch: 28 :loss: 0.16529765534618673 :acc: 0.9294253720385811
confusion:
[[0.82981761 0.04537602]
 [0.02520388 0.0996025 ]]
validation loss: 0.1553601029244336 :validation acc: 0.9346221590909092
validation confusion
[[0.82853363 0.03971116]
 [0.02568924 0.10606597]]
time: 48070
********************************
epoch: 29 :loss: 0.16475779328444232 :acc: 0.9297552150544303
confusion:
[[0.82980493 0.04502396]
 [0.02521656 0.09995456]]
validation loss: 0.1560634585944089 :validation acc: 0.9348693181818183
validation confusion
[[0.8290787  0.03994476]
 [0.02514416 0.10583237]]
time: 48131
********************************
epoch: 30 :loss: 0.1642980332

********************************
epoch: 54 :loss: 0.15880497235413557 :acc: 0.9322644669032497
confusion:
[[0.83020682 0.04292195]
 [0.02481466 0.10205656]]
validation loss: 0.1513261163776571 :validation acc: 0.9358346841577541
validation confusion
[[0.83085823 0.04077345]
 [0.02336463 0.10500369]]
time: 48026
********************************
epoch: 55 :loss: 0.15865245992190216 :acc: 0.9323757062322151
confusion:
[[0.83035525 0.04296428]
 [0.02466623 0.10201423]]
validation loss: 0.15090585459362377 :validation acc: 0.9362294451871659
validation confusion
[[0.82989453 0.0394547 ]
 [0.02432834 0.10632244]]
time: 48072
********************************
epoch: 56 :loss: 0.15860995881633672 :acc: 0.9324448818327709
confusion:
[[0.83030435 0.04283568]
 [0.02471714 0.10214284]]
validation loss: 0.15140703130852093 :validation acc: 0.9358219418449196
validation confusion
[[0.83243059 0.04239224]
 [0.02179227 0.10338489]]
time: 48218
********************************
epoch: 57 :loss: 0.1583404

********************************
epoch: 81 :loss: 0.15583332032645675 :acc: 0.9336190290806365
confusion:
[[0.8303799  0.04173663]
 [0.02464158 0.10324189]]
validation loss: 0.14983908832073212 :validation acc: 0.9365898228609626
validation confusion
[[0.83112898 0.04032196]
 [0.02309388 0.10545518]]
time: 47977
********************************
epoch: 82 :loss: 0.15575139523913326 :acc: 0.9337179713867378
confusion:
[[0.8305119  0.04177396]
 [0.02450958 0.10320456]]
validation loss: 0.14970279092138464 :validation acc: 0.936514120989305
validation confusion
[[0.82656693 0.03581991]
 [0.02765594 0.10995722]]
time: 48044
********************************
epoch: 83 :loss: 0.15560360028319162 :acc: 0.9336854800517833
confusion:
[[0.83029327 0.04158337]
 [0.02472821 0.10339515]]
validation loss: 0.14981765421954069 :validation acc: 0.936560995989305
validation confusion
[[0.82740276 0.03656287]
 [0.02682011 0.10921426]]
time: 47984
********************************
epoch: 84 :loss: 0.15564109